spring.application.name=BACK-END-JAVA

# URL de conexão (substitua 'meu_banco' pelo nome do seu banco de dados)
spring.datasource.url=jdbc:postgresql://localhost:5432/salao_renata

# Suas credenciais de acesso
spring.datasource.username=postgres
spring.datasource.password=MSF01e01

# Configurações do JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true