
# spring.datasource.url=jdbc:postgresql://localhost:5432/seu_banco
# spring.datasource.username=seu_usuario
# spring.datasource.password=sua_senha
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================

spring.datasource.url=jdbc:h2:mem:tukotomi_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Recria o banco sempre que rodar e aplica o data.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Habilita o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console