name: BACK-END-JAVA

on:
  workflow_dispatch:

jobs:
  build:
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/build-java.yml@main
    with:
      sonar_project_key: "Pesquisa-e-Inovacao-Grupo-8_${{github.repository}}"
    secrets: inherit


