name: BACK-END-JAVA

on:
  workflow_dispatch:

jobs:
  build:
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/build-java.yml@main
    with:
      GITHUB_REPOSITORY: ${{ github.repository.name }}
      GITHUB_ORGANIZATION: ${{ github.organization }}
    secrets: inherit


