name: BACK-END-JAVA

on:
  workflow_dispatch:

jobs:
  build:
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/build-java.yml@main
    with:
      sonar_project_key: ${{ github.repository }}
      sonar_organization: "pesquisa-e-inovacao-grupo-8"
    secrets: inherit


